### ISSUE TITLE
Error when html variable is not specified

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-autoresponder#10]
The `html` request variable is optional, however the integration results in an error when it is not specified.

![pastedgraphic-2](https://cloud.githubusercontent.com/assets/569/8705844/e2ea26c2-2af1-11e5-8948-2ac31362ad8d.png)

**Comment by ros3bud** [comment]
Ohh, I think this is because when it's empty, it's passed as null and aws does not like that.

**Comment by alexkwolfe** [comment]
That's right
