### ISSUE TITLE
Fromname field doesn't properly populate in the sent email

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-integration-autoresponder#13]
In her testing, Karalyn discovered that the From Name doesn't actually populate in the email. The expectation is that the flow creator would enter a name to show up as the sender. So, while the FROM address will be no-reply@offerconfirmation.com, the FROM name could be Jane Doe or Infamil. So the email would have this in the From line: `Jane Doe <no-reply@offerconfirmation.com>`

**Comment by kcaponeAP** [comment]
For the lead: https://next.staging.leadconduit.com/events/55b8ee1052bef5107222c3c6

I specified Sasha Donnelly as the sender's name:

![screen shot 2015-07-30 at 11 32 31 am](https://cloud.githubusercontent.com/assets/8238417/8988951/b2059532-36ae-11e5-88a9-927a5d95c063.png)


The result I received in email was.. attached. No sender's name

![screen shot 2015-07-30 at 11 29 59 am](https://cloud.githubusercontent.com/assets/8238417/8988874/649702e0-36ae-11e5-8546-991c0154be66.png)
