### ISSUE TITLE
Reorder mappings

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-integration-autoresponder#14]
Can we change the order of the field mappings for the integration so they appear in an order similar to an email client?

* Fromname
* CC
* BCC
* Subject
* Text
* HTML

**Comment by ros3bud** [comment]
@alexj, what about the to address?

**Comment by alexj** [comment]
I don't recall seeing "To:" in the mappings field list by default. Since it is an autoresponder, I would expect that the leads email address would automatically be used for that value. Is there a reason it would need to be mapped otherwise?

**Comment by ros3bud** [comment]
No, there is not - and yes lead.email is the value which should be mapped. Ok, thanks.
